### ISSUE TITLE
Issues with updated NuGet packages

### ISSUE THREAD

**Issue by JMHaro** [MisterJames/BootstrappingMvc#1]
James,  I was using your project to try to help learn more with the Bootstrap (since I'm fairly new with MVC itself also).  When I followed your video's, my project would just not work (virutally got no bootstrap enabled displayes).  I downloded this project which worked fine for me so I wanted to find out what was different between it and what I had done from the video.  Even after I made sure most all of my code matched your project mine would still not work.  So I then took your project and started updating the NuGet packages.  I tested it after updating some of the basic packages like Bootstrap and it still worked.  But after I updated all of the packages to match what a current new project created in VS2012 might have, then your project quit working also.  So is there any chance in trying to learn what is needed to make your bootstrap project work with the current NuGet packages in the project?

Added note:  I was able to isolate down the update package causing the issue is the Microsoft.AspNet.Web.Optimization.  Your project is running against version 1.0.0-beta2.  When this is updated to version 1.0.0 the project no longer displays the bootstrap items.  I have recompiled the entire project but nothing helps.  If you can look into this I sure would like to know the answer to correct this issue.

Thank you,

**Comment by MisterJames** [comment]
Hey @JMHaro, thanks for the note.

So, from the videos to today, there's a lot different from how Bootstrap was wired into the site, how the default site works in VS2010/2012, and the Bootstrap library itself.

I understand the desire to get that working.  If you post what you have now into GitHub, I'd be happy to fork and take a look and see if I can suggest something.

If you want to look at things on your own, I would suggest the following:
- check the bundle config
- make sure the JS libraries are named consistantly
- make sure you're rendering the bundle in your pages
- depending on the version of jQuery, you man need jQuery Migrate
- check your F12 tools for JS or network (404) errors

Hope this helps some, and thanks for following along.  I'm hoping to get back to the videos soon!

**Comment by MisterJames** [comment]
Btw...if you do choose to post it up on GitHub, let me know the repo and I'll fork and get it working for you.

Cheers.

**Comment by JMHaro** [comment]
Thanks James, I'll look into doing your recommendations.
